services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports: 
      - 27017:27017
    command: ["--replSet", "rs0", "--bind_ip_all"]  
    volumes:
      - db-data:/data/db
    networks:
      - sm-post      

volumes:
  db-data:
    driver: local

networks:
  sm-post:
    external: true

# mongosh

# use admin

# rs.initiate()

# db.createUser({
#   user: "admin",
#   pwd: "password", 
#   roles: [ { role: "root", db: "admin" } ]
# })

# cfg = rs.conf()
# cfg.members[0].host = "mongo:27017"
# rs.reconfig(cfg, { force: true })


# mongodb://admin:password@mongo:27017/?replicaSet=rs0&authSource=admin